<?php

namespace AppBundle\Repository;

/**
 * AmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmisRepository extends \Doctrine\ORM\EntityRepository
{
}
