<?php

namespace AppBundle\Repository;

/**
 * contenuPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contenuPageRepository extends \Doctrine\ORM\EntityRepository
{
}
