<?php

namespace AppBundle\Repository;

/**
 * contenuAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contenuAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
