<?php

namespace AppBundle\Repository;

/**
 * ParticipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipeRepository extends \Doctrine\ORM\EntityRepository
{
}
