# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   user_registration:
      class: UserBundle\Form\Type\RegistrationFormType
      arguments: [%fos_user.model.user.class%]
      tags:
         -  { name: form.type }